config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :users
  resources :messages

  get 'login' => 'sessions#new'
  post 'dologin' => 'sessions#create'

  get 'log_out' => 'sessions#destroy'

  get 'friend_request/:id' => 'users#friend_request', as: :friend_request

  get 'auth/:provider/callback' => 'sessions#callback'
  get 'auth/failure' => 'sessions#fail_callback'

end

app/models/friendable.rb
class Friendable < ActiveRecord::Base
  belongs_to :from, class_name: "User"
  belongs_to :to, class_name: "User"
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :recipient, class_name: "User"
  belongs_to :sender, class_name: "User"

  validates :content, presence: true
  validates :recipient, presence: true
  validates :sender, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_many :incomming_messages, class_name: "Message", foreign_key: "recipient_id"
  has_many :outcomming_messages, class_name: "Message", foreign_key: "sender_id"

  has_many :friendables, :class_name => "Friendable", :foreign_key => "from_id"
  has_many :passive_friendables, :class_name => "Friendable", :foreign_key => "to_id"
  has_many :active_friends, -> { where(friendables: {accepted: true}) }, :through => :friendables, :source => :to
  has_many :passive_friends, -> { where(friendables: {accepted: true}) }, :through => :passive_friendables, :source => :from
  has_many :pending_friends, -> { where(friendables: {accepted: false}) }, :through => :friendables, :source => :to
  has_many :requested_friendables, -> { where(friendables: {accepted: false}) }, :through => :passive_friendables, :source => :from

  validates_uniqueness_of :email
  validates :name, presence: true

  def self.from_omniauth(auth)
    # Note that Facebook sometimes does not return email,
    # in that case you can use facebook-id@facebook.com as a workaround
    # email = auth[:info][:email] || "#{auth[:uid]}@facebook.com"
    email = "#{auth[:uid]}@facebook.com" # Always use fake email to avoid modify model to add provider field and other validations
    user = where(email: email).first_or_initialize

    # Set other properties on user here.
    user.name = auth[:info][:name]
    user.image_url = auth[:info][:image]

    # Finally, return user
    user.save(:validate => false) && user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :sign_in?

  def current_user
    return unless session[:user_id]
    User.find(session[:user_id])
  end

  def sign_in?
    current_user
  end

  def require_login
    redirect_to login_path, flash: {error: 'You must sign in first to see this page.'} unless sign_in?
  end

  def skipped_if_login
    redirect_to messages_path if sign_in?
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_login

  def index
    @type = params[:type] || 'incomming'
    if @type == 'incomming'
      @messages = current_user.incomming_messages.order created_at: :desc
    elsif @type == 'outcomming'
      @messages = current_user.outcomming_messages.order created_at: :desc
    else
      @messages = []
    end
  end

  def show
    message_id = params[:id]
    @message = Message.find(message_id)
    @read = @message.read
    unless (@message.recipient == current_user)
      redirect_to messages_path, flash: {error: 'You are not recipient of this message'}
    else
      unless @read
        @message.read = true
        @message.save!
      end
    end
  end

  def new
    @friends = current_user.active_friends + current_user.passive_friends
  end

  def create
    recipient_id = params[:message][:recipient_id]
    content = params[:message][:content]

    if recipient_id.nil? || recipient_id.empty?
      redirect_to new_message_path, flash: {error: 'Cannot send message. You must choose recipient and type content.'}
      return
    end

    message = Message.new
    message.content = content
    recipient = User.find(recipient_id)
    message.recipient = recipient
    message.sender = current_user

    if message.save
      redirect_to messages_path(type: 'outcomming'), flash: {success: "Send message to #{recipient.name} successfully"}
    else
      redirect_to new_message_path, flash: {error: 'Cannot send message. You must choose recipient and type content.'}
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :skipped_if_login, only: [:new]

  def new
  end

  def create
    email = params[:user][:email]
    password = params[:user][:password]

    user = User.find_by_email(email)

    if user && user.authenticate(password)
      session[:user_id] = user.id
      redirect_to messages_path, flash: {success: "Welcome #{user.name}"}
    else
      redirect_to login_path, flash: {error: "Email or password is incorrect. Please try again!"}
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  def callback
    if user = User.from_omniauth(env["omniauth.auth"])
      session[:user_id] = user.id
      redirect_to messages_path, flash: {success: "Welcome #{user.name}"}
    else
      redirect_to root_path, flash: {error: "Cannot login with Facebook. Please try again!"}
    end
  end

  def fail_callback
    message = params[:message]
    redirect_to root_path, flash: {error: "Login with Facebook fail: #{message}"}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, only: [:index]
  before_action :skipped_if_login, only: [:new]

  def new
    @user = User.new
  end

  def index
    @users = User.all.shuffle
  end

  def create
    @user = User.new(get_user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to messages_path, flash: {success: "Welcome #{@user.name}"}
    else
      redirect_to root_path, flash: {error: "Oops! Something goes wrong. #{@user.errors.messages.collect {|k, v| "#{k}: #{v.join(' and ')}"}.join(', ')}"}
    end
  end

  def friend_request
    @friendable = current_user.friendables.build(:to_id => params[:id], accepted: "true") # accept by default
      if @friendable.save
        redirect_to messages_path, flash: {success: "Friend added"}
      else
        redirect_to messages_path, flash: {error: "Unable to request friendable"}
      end
  end

  private

  def get_user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :skipped_if_login, only: [:index]

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for flash_type
    {success: 'alert-success', error: 'alert-danger', warning: 'alert-warning'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "app-message text-center alert #{bootstrap_class_for(msg_type)} fade in") do
        concat content_tag(:button, '&times;'.html_safe, class: 'close close-message', data: {dismiss: 'alert'})
        concat message
      end)
      flash.clear
    end
    nil
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoderschoolAssignment2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <%= flash_messages %>
    <nav class="navbar navbar-light bg-faded">

        <!-- Toggle Button -->
        <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#nav-content">
            &#9776;
        </button>
        <!-- Nav Content -->
        <div class="collapse navbar-toggleable-xs" id="nav-content">
            <a class="navbar-brand" href="/"><%= image_tag "logo-small.png" %></a>
            <ul class="nav navbar-nav">
                <% unless sign_in? %>
                    <li class="nav-item">
                        <%= link_to 'Sign Up', root_path, class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <%= link_to 'Sign In', login_path, class: "nav-link" %>
                    </li>
                <% else %>
                    <li class="nav-item">
                        <%= link_to 'Sign Out', log_out_path, id: 'sign-out', class: "nav-link" %>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= new_message_path %>">New message</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= users_path %>">Add friends</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="<%= messages_path.concat('?type=outcomming') %>">Sent messages</a>
                    </li>
                <% end %>
            </ul>
        </div>
    </nav>

    <%= yield %>

    <footer class="footer-12">
        <div class="container">
            Chat-Chit everywhere
        </div>
    </footer>

</body>
</html>

app/views/messages/index.html.erb
<div class="container">
    <h2 class="title"><%= "#{@type.capitalize} Messages" %></h2>

    <table class="table">
        <thead class="thead-default">
            <tr>
                <th>#</th>
                <% if @type == 'incomming' %>
                    <th>From</th>
                <% end %>
                <% if @type == 'outcomming' %>
                    <th>To</th>
                <% end %>
                <th>Sent date</th>
                <% if @type == 'incomming' %>
                    <th>Action</th>
                <% end %>
                <% if @type == 'outcomming' %>
                    <th>Status</th>
                <% end %>
            </tr>
        </thead>
        <tbody>
            <% @messages.each_with_index do |message, index| %>
                <tr class="<%= "unread" unless message.read %>">
                    <td><%= index + 1 %></td>
                    <% if @type == 'incomming' %>
                        <td><%= message.sender.name %></td>
                    <% end %>
                    <% if @type == 'outcomming' %>
                        <td><%= message.recipient.name %> </td>
                    <% end %>
                    <td><%= message.created_at.strftime("%b %d, %Y") %></td>
                    <% if @type == 'incomming' %>
                        <% if message.read %>
                            <td>Read</td>
                        <% else %>
                            <td><%= link_to "Read", message %></td>
                        <% end %>
                    <% end %>
                    <% if @type == 'outcomming' %>
                        <% if message.read %>
                            <td><%= "Read on #{message.updated_at.strftime("%b %d, %Y")}" %></td>
                        <% else %>
                            <td>Unread</td>
                        <% end %>
                    <% end %>
                </tr>
            <% end %>
        </tbody>
    </table>

</div>

app/views/messages/new.html.erb
<div class="container">
    <h2 class="title">Send message</h2>

    <div class="send-message-form">
        <%= form_for(Message.new) do |f| %>
            <fieldset class="form-group">
                <%= f.label :recipient %>
                <%= f.collection_select :recipient_id, @friends, :id, :name, {include_blank: true}, class: 'form-control' %>
            </fieldset>

            <fieldset class="form-group">
                <%= f.label :content %>
                <%= f.text_area :content, class: "form-control", rows: 4 %>
            </fieldset>

            <button type="submit" class="btn btn-primary">Send</button>
        <% end %>
    </div>

</div>

app/views/messages/show.html.erb
<div class="container">
    <h2 class="title"><%= "Message from #{@message.sender.name}" %></h2>

    <% unless @read %>
        <blockquote class="blockquote">
            <p><%= @message.content %></p>
            <footer><%= "Since #{@message.created_at.strftime("%b %d, %Y")}" %></footer>
        </blockquote>
    <% else %>
        <div class="alert alert-danger" role="alert">
            <strong>Oops!</strong> You have read this message already.
        </div>
    <% end %>

</div>

app/views/users/_form.html.erb
<div class="signup-form">
    <%= form_for(User.new) do |f| %>
        <div class="form-group">
            <%= f.text_field 'email', class: 'form-control', placeholder: 'Your E-mail' %>
        </div>
        <div class="form-group">
            <%= f.text_field 'name', class: 'form-control', placeholder: 'Name' %>
        </div>
        <div class="form-group">
            <div class="half-width password">
                <%= f.password_field 'password', class: 'form-control', placeholder: 'Password' %>
            </div>
            <div class="half-width password-confirmation">
                <%= f.password_field 'password_confirmation', class: 'form-control', placeholder: 'Confirmation' %>
            </div>
        </div>
        <div class="form-group">
            <%= f.submit 'Sign Up', class: 'btn btn-block btn-info' %>
            <a id= "sign-in" href="auth/facebook" class="btn btn-block btn-success">Log In with Facebook</a>
        </div>
    <% end %>
</div>

app/views/users/_user.html.erb
<div class="col-xs-12 col-md-4">
    <div class="card card-<%= cycle('male', 'female') %>">
        <%= image_tag user.try(:image_url) || 'no-avatar.png', class: 'avatar' %>
        <div class="card-block">
            <h4 class="card-title"><%= user.try(:name) %></h4>
            <%= link_to "Make friend", friend_request_path(id: user.id), class: "btn btn-primary-outline" %>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<div class="container users-index">
    <% @users.in_groups_of(3) do |group| %>
        <div class="row">
            <%= render partial: 'user', collection: group.compact %>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <%= render 'form' %>
        </div>
    </div>
</div>

app/views/welcome/index.html.erb
<section class="header-11-sub">
    <div class="background">&nbsp;</div>
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <h3>The CoderChat for everyone</h3>
                <p>CoderChat is the SnapChat-like app just for learning Ruby on Rails purpose.</p>
                <%= render 'users/form' %>
                <div class="additional-links">By signing up you agree to <a href="#">Terms of Use</a> and <a href="#">Privacy</a></div>
            </div>
            <div class="col-sm-7 col-sm-offset-1 player-wrapper">
                <div class="player">
                    <%= image_tag "connect.png" %>
                </div>
            </div>
        </div>
    </div>
</section>